spring.application.name=progInz_Seminar1

spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/proginz_seminar1
spring.datasource.username=andzekausk
spring.datasource.password=parole
spring.datasource.driver-class-name=com.mysql.jdbc.Driver